apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aggregator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anuddeeph1/test-remediator.git
    targetRevision: main
    path: apps/aggregator
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
